### ISSUE TITLE
Getting some random errors

### ISSUE THREAD

**Issue by ricardocasares** [gillbeits/gulp-fontello#3]
Most of the time the gulp task run without any issues, but I randomly get this errors:

``` javascript
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: invalid distance too far back
    at Zlib._handle.onerror (zlib.js:363:17)
```

``` javascript
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: invalid signature: 0xfb347713
    at ../project/node_modules/gulp-fontello/node_modules/unzip/lib/parse.js:59:13
    at processImmediate [as _immediateCallback] (timers.js:371:17)

```

``` javascript
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: stream.push() after EOF
  at readableAddChunk (../project/node_modules/gulp-fontello/node_modules/unzip/node_modules/readable-stream/lib/_stream_readable.js:168:15)
  at SliceStream.Readable.push (../project/node_modules/gulp-fontello/node_modules/unzip/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at SliceStream.Transform.push (../project/node_modules/gulp-fontello/node_modules/unzip/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at SliceStream.sliceFn (../project/node_modules/gulp-fontello/node_modules/unzip/node_modules/pullstream/pullstream.js:81:14)
  at SliceStream._transform (../project/node_modules/gulp-fontello/node_modules/unzip/node_modules/pullstream/node_modules/slice-stream/slicestream.js:28:10)
  at SliceStream.Transform._read (../project/node_modules/gulp-fontello/node_modules/unzip/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at SliceStream.Transform._write (../project/node_modules/gulp-fontello/node_modules/unzip/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (../project/node_modules/gulp-fontello/node_modules/unzip/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at clearBuffer (../project/node_modules/gulp-fontello/node_modules/unzip/node_modules/readable-stream/lib/_stream_writable.js:316:5)
  at onwrite (../project/node_modules/gulp-fontello/node_modules/unzip/node_modules/readable-stream/lib/_stream_writable.js:274:7)
```

**Comment by rootical** [comment]
Curios about the plugin not to break CI builds. 

@ricardocasares uses Ubuntu I guess,

I've not seen these issues on Mac.

**Comment by rootical** [comment]
@gillbeits, could you please check the issue?

**Comment by gillbeits** [comment]
@ricardocasares I was not able to reproduce this error.
